version: '3'
services:
  flask-app:
    build: .
    ports:
      - "8888:8888"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
